# Generated by Django 4.2.5 on 2023-10-08 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking_brain', '0008_trash_alter_passenger_return_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='passenger',
            name='Return_date',
            field=models.DateField(null=True),
        ),
    ]
